### ISSUE TITLE
You cannot log in to another account after logging out

### ISSUE THREAD

**Issue by yancihh** [Azure-Samples/ms-identity-javascript-react-spa#17]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [√ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Run the project→Sign in→Sign in using Popup→Sign Out

### Any log messages given by the failure
>none

### Expected/desired behavior
>After logging out, click Login to select other accounts to log in

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Window 11
### Versions
>
KB5009566
### Mention any other details that might be useful
none
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by derisen** [comment]
hey @yancihh, apologies for the late response. This sample lacks an account selection logic for the sake of simplicity -take a look at this [sample here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/react-router-sample) instead, in particular to [index.ts](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/db858a9ef01e9fb4022da75dcdc8f28713099d89/samples/msal-react-samples/react-router-sample/src/index.js#L18) and [AccountPicker.tsx](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-react-samples/react-router-sample/src/ui-components/AccountPicker.jsx). You'll have to come up with your own account selection logic eventually, but this sets you up at the right path (see also the [account docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/accounts.md)).

Closing this for now, but feel free to reopen if you have any issues.
