### ISSUE TITLE
Cannot Sign-in on Microsoft Teams Desktop App

### ISSUE THREAD

**Issue by tiennguyen1293** [Azure-Samples/ms-identity-javascript-react-spa#18]
### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Clone the repo and deployment to someone's domain
> Create and Upload custom App to Microsoft Teams Desktop App
> Try Sign-in with Popup or Sign-in with Redirect

### Any log messages given by the failure
> `App webApplicationInfo or resource not defined in manifest`
<img width="787" alt="image" src="https://user-images.githubusercontent.com/26110369/156524853-f1759df3-496a-47e4-8662-08b44829d59d.png">

### Expected/desired behavior
> Can Sign-in with Popup or Sign-in with Redirect

### OS and Version?
> Microsoft Teams Desktop App on OS v1.5.00.4767

### Versions
```
"@azure/msal-browser": "^2.22.0",
"@azure/msal-react": "^1.3.0",
```

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by derisen** [comment]
Hi @tiennguyen1293, apologies for late response. When using msal within the Teams framework you're supposed to let Teams handle any windows using its own API. Take a look at [this sample](https://github.com/pnp/teams-dev-samples/tree/main/samples/tab-sso/src/nodejs) where we show how to do it ([e.g.](https://github.com/pnp/teams-dev-samples/blob/main/samples/tab-sso/src/nodejs/src/components/ConsentPopup.js)). Let us know if you have any further questions.
