### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by rexkenley** [Azure-Samples/ms-identity-javascript-react-spa#29]
### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Clone, npm ci, follow setup instructions

### Any log messages given by the failure
> Access to fetch at 'https://developer.microsoft.com/graph' (redirected from 'https://graph.microsoft.com/') from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### Expected/desired behavior
> Get profile information

### OS and Version?
> Windows 10

I have tried using package.json proxy and manually setting up the proxy to no avail. What am I doing wrong?
https://create-react-app.dev/docs/proxying-api-requests-in-development/
https://www.npmjs.com/package/cors

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by derisen** [comment]
@rexkenley I'm not able to reproduce this. Would you mind sharing your app configuration and a code snippet where you are calling the Graph API? Curious why your request is going to `https://developer.microsoft.com/graph`

**Comment by rexkenley** [comment]
@derisen , is this what you need?

authConfig.js
![image](https://user-images.githubusercontent.com/10548251/192286255-891dfd79-47bb-4cdb-b98e-3ad2d2ff12a7.png)

graph.js
![image](https://user-images.githubusercontent.com/10548251/192285835-66f57742-e796-4663-8a92-0f26ee2f9f1b.png)

**Comment by derisen** [comment]
@rexkenley thanks! so it looks to me that you are not calling the right Graph API endpoint. In `authConfig.js` line 64, `graphMeEndpoint` should have the value `https://graph.microsoft.com/v1.0/me`. More on the `/me` endpoint [here](https://learn.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http)

**Comment by rexkenley** [comment]
@derisen Thank you very much. That was it.
