### ISSUE TITLE
What is the Best Practice for Implementing Authorization Based on the Authenticated User's Identity?

### ISSUE THREAD

**Issue by pjchungmd** [Azure-Samples/ms-identity-javascript-react-spa#3]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
- [X] question
```

### Minimal steps to reproduce
> The view of the app can be modified by using the `<AuthenticatedTemplate>` and `<UnauthenticatedTemplate>` tags, however what is the appropriate way to determine whether an authenticated user can go to certain pages or not. For example, I have been experimenting by using the following:

    import React, { useEffect, useState } from "react";
    import { 
      AuthenticatedTemplate, 
      UnauthenticatedTemplate,
      useAccount,
      useMsal,
    } from "@azure/msal-react";
    
    const Home = () => {
      const { instance, accounts, inProgress } = useMsal();
      const account = useAccount(accounts[0] || {});
    
      return (
          <div className="container-sm">
            <AuthenticatedTemplate>
              // Can also use ID 
              {account && account.name === "Test, User" && (
                <div>
                  Hi There
                </div>
              )}
              {account && account.name !== "Test, User" && (
                <div>
                  Nothing to see
                </div>
              )}
            </AuthenticatedTemplate>
            <UnauthenticatedTemplate>
              <h5 className="card-title">
                Please sign-in to see your profile information.
              </h5>
            </UnauthenticatedTemplate>
          </div>
      );
    };
    
    export default Home;

This does work as expected, but it seems like from a security standpoint, a bad idea because this check is happening on the client side. Should the list of "authorized" users be queried from the server side first and checked against that? Or does `msal` provide that kind of functionality? Either way, what would be the "appropriate" approach to implementing authorization based on the identity of the user? Thank you!

**Comment by derisen** [comment]
@pjchungmd so there could be a number of ways to achieve this, but I would recommend using [App Roles](https://docs.microsoft.com/azure/active-directory/develop/howto-add-app-roles-in-azure-ad-apps) feature to implement [Role-based Access Control](https://docs.microsoft.com/azure/role-based-access-control/overview). 

And yes, you'll need a back-end service to properly implement this. We have a [set of samples](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-dotnetcore-webapi-roles-groups) using Angular on the front-end and .NET Core on the back-end that shows this (look at [Chapter 1](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-dotnetcore-webapi-roles-groups/tree/master/chapter1)). There is plan to do the same with React and Node.js soon, but it's not out yet.

Let me know if that helps.

**Comment by derisen** [comment]
Closing. Let us know if you need further help.
