### ISSUE TITLE
Cannot sign in on SPA at http://127.0.0.1:3000 (MS tenant)

### ISSUE THREAD

**Issue by dluc** [Azure-Samples/ms-identity-javascript-react-spa#34]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

I followed the tutorial at https://learn.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-react to add auth to a React app but the auth flow doesn't work. The app is on MS tenant, I tried both popup and redirect sign in.

```
"replyUrlsWithType": [
{
	"url": "http://localhost:3000",
	"type": "Spa"
},
```

![image](https://user-images.githubusercontent.com/371009/206934169-86d757c0-f2e8-486f-a878-ece77ac6e7bb.png)

### Minimal steps to reproduce
* Create AAD app on MS tenant with SPA redirect URI http://localhost:3000
** Implicit grant ID Tokens
** Single tenant
* Download this repo and configure authConfig.js
* yarn install && yarn start
* Open Edge inPrivate window
* Go to http://localhost:3000
* Try to sign in with Redirect and Popup, neither work

### Any log messages given by the failure

The request to fetch a token fails:

![image](https://user-images.githubusercontent.com/371009/206934076-a89cf034-65b4-447a-82ba-becd6578a29c.png)

POST 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/token' 

{"error":"invalid_request","error_description":"AADSTS9002326: Cross-origin token redemption is permitted only for the 'Single-Page Application' client-type. Request origin: 'http://localhost:3000'.\r\nTrace ID: ...\r\nCorrelation ID: ...\r\nTimestamp: ...","error_codes":[9002326],"timestamp":"...","trace_id":"...","correlation_id":"...","error_uri":"https://login.microsoftonline.com/error?code=9002326"}

### OS and Version?
MacOS Ventura 13, Edge

**Comment by dluc** [comment]
FYI I tried a new AAD app and everything works, so I suspect some settings in the app manifest affect this behavior. It's very hard knowing why, considering how long it takes for manifest changes to propagate, and the many small differences.

**Comment by salman90** [comment]
@dluc , thanks for reaching out. If you create a new application in Azure AD, the application is working as expected, correct? If so, please ensure you don't have [two different types of applications with the same redirect URI](https://learn.microsoft.com/en-us/azure/active-directory/develop/reply-url#localhost-exceptions) in your application registration.

**Comment by salman90** [comment]
@dluc closing the issue due to inactivity.

**Comment by salman90** [comment]
@dluc closing the issue due to inactivity.
