### ISSUE TITLE
Question - is this the latest react sample?

### ISSUE THREAD

**Issue by AlexBeyd** [Azure-Samples/ms-identity-javascript-react-spa#38]
Hey @salman90 !
This is Alex. How are you doing guys?

I'm looking for latest AAD sample for react. Is this one?

Nice to see you!

**Comment by salman90** [comment]
Hi [@AlexBeyd](https://github.com/AlexBeyd). It's good to hear from you. This sample is up to date with the latest AAD updates. If you're looking for additional scenarios and resources, take a look at the following:
1- [React tutorials](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial).
2- [React docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-react/docs).

Let me know need anything else.

**Comment by AlexBeyd** [comment]
Thanks man. Say hi to the team
