### ISSUE TITLE
CORS error when trying to use an existing app registration

### ISSUE THREAD

**Issue by Abe-Froman** [Azure-Samples/ms-identity-javascript-react-spa#6]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

Hoping someone can explain, but this sample works just fine when I create a new app registration and set the SPA Reply URL accordingly. However, we are trying to migrate an existing application, already in production, from ADAL to MSAL and when we add a SPA platform to that app registration, with the same reply URL, it's throwing the CORS error _most of the time_.  Every now and then it will log me in correctly. I've seen it succeed after as few as 3 and after as many as 15 attempts though most of the time it fails until my account seemingly becomes locked/disabled for a period of time.

Is there something about older app registrations that render this sample unusable?

**Comment by derisen** [comment]
@Abe-Froman you have to make sure that Azure AD is able to distinguish your redirect URIs and match the correct auth flow with them. See the [documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/reply-url#localhost-exceptions):

> Due to ephemeral port ranges often required by native applications, the port component (for example, :5001 or :443) is ignored for the purposes of matching a redirect URI. As a result, all of these URIs are considered equivalent:
> http://localhost/MyApp
> http://localhost:1234/MyApp
> http://localhost:5000/MyApp
> http://localhost:8080/MyApp
> From a development standpoint, this means a few things:
> 
> Do not register multiple redirect URIs where only the port differs. The login server will pick one arbitrarily and use the behavior associated with that redirect URI (for example, whether it's a web-, native-, or spa-type redirect).
> 
> This is especially important when you want to use different authentication flows in the same application registration, for example both the authorization code grant and implicit flow. To associate the correct response behavior with each redirect URI, the login server must be able to distinguish between the redirect URIs and cannot do so when only the port differs.
> 
> To register multiple redirect URIs on localhost to test different flows during development, differentiate them using the path component of the URI. For example, http://localhost/MyWebApp doesn't match http://localhost/MyNativeApp.

Does that help?

**Comment by Abe-Froman** [comment]
@derisen Ugh, yes, this helps immensely. We'd left localhost:3000 as a redirect URI on the web platform so as not to break our existing dev environment and added localhost:5000 as a SPA redirect.

I confirmed now that removing the localhost:3000 URI unbreaks us.
